(defun el2clj-replace-hash-maps (buf)
  (set-buffer buf)
  (beginning-of-buffer)
  (while (search-forward "{" nil t)
    (replace-match "{" "(el2clj-make-hash-table "))
  (beginning-of-buffer)
  (while (search-forward "}" nil t)
    (replace-match "}" ")")))

(defun el2clj-compile-buffer ()
  (interactive)
  (let* ((cur-buf-substring (buffer-substring-no-properties 1 (point-max)))
         (cur-buf-name (buffer-file-name))
         (new-buf-name (concat cur-buf-name "2clj"))
         (new-buf (generate-new-buffer (generate-new-buffer-name "compilation-buffer"))))
    (set-buffer new-buf)
    (insert cur-buf-substring)
    (write-file new-buf-name)
    (el2clj-replace-hash-maps new-buf)))
